
(*
  CGC FeynArts Script — SM Content Verification
  Auto-generated by cgc.engine.feynarts_backend
*)

<< FeynArts`;

$LoadFeynArts = True;
$LoadPhi = False;
$LoadTARCER = False;
InitializeModel[SM, GenericModel -> Lorentz];

(* ── SM Particle Content ── *)
(* M$ClassesDescription has form: {class -> {{particle, mass}, ...}, ...} *)
classCount = Length[M$ClassesDescription];
particleData = Table[
  ToString /@ {{"class", i, M$ClassesDescription[[i, 1]]},
                {"n_particles", Length[M$ClassesDescription[[i, 2]]]},
                {"generic", ToString[M$GenericType[i]]}},
  {i, 1, classCount}
];

(* ── SM Vertex Count ── *)
(* M$CouplingMatrices: list of coupling rules *)
vertexCount = Length[M$CouplingMatrices];

(* ── 1-loop 2→2 skeleton topologies (no field insertion) ── *)
topos = CreateTopologies[1, 2 -> 2, ExcludeTopologies -> WFCorrections];
topoCount = Length[topos];
topoSummary = Table[
  {{"id", i},
   {"n_props", Length[topos[[i, 1]]]},
   {"n_external", Length[Cases[topos[[i, 1]], Propagator[Incoming|Outgoing][__]]]},
   {"n_loop", Length[Cases[topos[[i, 1]], Propagator[Loop[_]][__]]]}},
  {i, 1, Min[topoCount, 100]}
];

(* ── Export ── *)
exportData = {{
  "model" -> "SM",
  "n_classes" -> classCount,
  "n_vertices" -> vertexCount,
  "n_topologies" -> topoCount,
  "particles" -> particleData,
  "topologies" -> topoSummary
}};

Export["D:/论文撰写/Conservation-Guided Classification/output/feynarts_test/feynarts_output.json", exportData, "JSON"];
Print["FeynArts OK: ", classCount, " classes, ", vertexCount, " vertices, ", topoCount, " topologies"];
Exit[0];
