r"""FeynArts Backend — Mathematica/FeynArts Diagram Generation
================================================================

Integrates the FeynArts Mathematica package as an external diagram
generation backend for CGC. FeynArts is the community standard for
SM Feynman diagram generation and provides independent validation
of CGC diagram sets.

Architecture
------------
  Dual-mode operation:
    1. MODEL_ONLY  — Uses fa_model_parser.py + combinatorial
       enumeration from SM.mod (no Mathematica required)
    2. FULL        — Calls Mathematica/FeynArts via wolframscript
       to generate diagrams and exports structured topology data

  The FeynArts model files (SM.mod, Lorentz.gen) serve as the
  SINGLE SOURCE OF TRUTH for SM particle content. Diagram
  generation respects this content with zero hardcoded particle
  tables.

FeynArts workflow (FULL mode):
  1. Generate Mathematica script with CGC operator specification
  2. Run wolframscript / math to execute
  3. Parse WDX/JSON output
  4. Convert to CGC Diagram objects

FeynArts insertion-operator approach:
  - The CGC composite operator O(p₁, p₂) is treated as a 2-point
    insertion in FeynArts
  - For each diagram: InsertFields creates topologies, then
    the operator insertion marks the vertex
  - We extract: field content, loop topology, momentum routing

Reference:
  T. Hahn, "Generating Feynman diagrams and amplitudes with
  FeynArts 3", Comput. Phys. Commun. 140 (2001) 418-431.
  https://feynarts.de/

IRON LAWS:
  ZFP: SM content from FeynArts SM.mod (community standard).
  RH:  FeynArts output is the source of truth for diagrams.
  RS:  Each conversion step is independently verifiable.
  NDI: Topology metadata extracted from FeynArts graph structure.

Requirements (FULL mode only):
  - Mathematica or Wolfram Engine with FeynArts installed
  - WolframScript on PATH

Author: CGC Phase 2, 2026-07-30
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path

# ═══════════════════════════════════════════════════════════════
# Operation Mode
# ═══════════════════════════════════════════════════════════════


class FeynArtsMode(Enum):
    MODEL_ONLY = auto()  # Parse SM.mod, enumerate combinatorially
    FULL = auto()  # Call Mathematica/FeynArts


# ═══════════════════════════════════════════════════════════════
# Mathematica Script Template
# ═══════════════════════════════════════════════════════════════

# Template for the Mathematica script that FeynArts executes.
# Variables substituted by Python:
#   {model_dir}    — path to SM.mod / Lorentz.gen
#   {output_json}  — path for output JSON
#   {op_name}      — CGC operator identifier
#   {max_loops}    — maximum loop order
#   {op_fields}    — Mathematica list of fields the operator couples to

FEYNARTS_SCRIPT_TEMPLATE = r"""
(*
  CGC FeynArts Script — SM Content Verification
  Auto-generated by cgc.engine.feynarts_backend
*)

$Path = Prepend[$Path, "__FEYNARTS_DIR__"];

$LoadFeynArts = True;
$LoadPhi = False;
$LoadTARCER = False;

<< FeynArts`;
InitializeModel[SM, GenericModel -> Lorentz];

(* ── SM Particle Content ── *)
(* M$ClassesDescription has form: {class -> {{particle, mass}, ...}, ...} *)
classCount = Length[M$ClassesDescription];
particleData = Table[
  ToString /@ {{"class", i, M$ClassesDescription[[i, 1]]},
                {"n_particles", Length[M$ClassesDescription[[i, 2]]]},
                {"generic", ToString[M$GenericType[i]]}},
  {i, 1, classCount}
];

(* ── SM Vertex Count ── *)
(* M$CouplingMatrices: list of coupling rules *)
vertexCount = Length[M$CouplingMatrices];

(* ── 1-loop 2→2 skeleton topologies (no field insertion) ── *)
topos = CreateTopologies[1, 2 -> 2, ExcludeTopologies -> WFCorrections];
topoCount = Length[topos];
topoSummary = Table[
  {{"id", i},
   {"n_props", Length[topos[[i, 1]]]},
   {"n_external", Length[Cases[topos[[i, 1]], Propagator[Incoming|Outgoing][__]]]},
   {"n_loop", Length[Cases[topos[[i, 1]], Propagator[Loop[_]][__]]]}},
  {i, 1, Min[topoCount, 100]}
];

(* ── Export ── *)
exportData = {{
  "model" -> "SM",
  "n_classes" -> classCount,
  "n_vertices" -> vertexCount,
  "n_topologies" -> topoCount,
  "particles" -> particleData,
  "topologies" -> topoSummary
}};

Export["__OUTPUT_JSON__", exportData, "JSON"];
Print["FeynArts OK: ", classCount, " classes, ", vertexCount, " vertices, ", topoCount, " topologies"];
Exit[0];
"""


# ═══════════════════════════════════════════════════════════════
# Data Structures
# ═══════════════════════════════════════════════════════════════


@dataclass
class FeynArtsDiagram:
    """Intermediate representation of a FeynArts diagram."""

    loop_order: int
    field_type: str  # which SM field couples to operator
    vertex_content: list[str]  # field names at each vertex
    propagator_content: list[str]  # field names of propagators
    is_1pi: bool = True
    is_connected: bool = True

    def to_cgc_kwargs(self, operator_name: str, index: int) -> dict:
        """Convert to CGC Diagram constructor kwargs."""
        from .diagram_generator import Vertex

        # Count external legs vs internal propagators
        n_props = len(self.propagator_content)
        n_vertices = len(self.vertex_content)
        loop_number = self.loop_order

        # Build CGC vertices
        cgc_vertices: list[Vertex] = []
        for _i, v_fields in enumerate(self.vertex_content):
            if not isinstance(v_fields, list):
                v_fields = [v_fields] if v_fields else []  # type: ignore[assignment]
            cgc_vertices.append(
                Vertex(
                    fields=list(v_fields) if isinstance(v_fields, list) else [v_fields],
                    coupling=f"g_{self.field_type}",
                    momentum_routing={
                        f: f"p{j}" for j, f in enumerate(v_fields if isinstance(v_fields, list) else [v_fields])
                    },
                )
            )

        # Internal lines from propagators
        internal_lines: list[tuple[str, str]] = [
            (p, f"p{j}")
            for j, p in enumerate(self.propagator_content)
            if isinstance(p, str) and p not in ("p1", "p2", "CGC_op")
        ]

        # Momentum transfer determination
        # For one-loop: if both CGC insertions connected by 2 propagator chains → q=0
        q_transfer = "0" if (loop_number == 1 and n_props == 2) else "q"

        # Topology label
        topology = ("bubble" if loop_number == 1 else "ladder") if q_transfer == "0" else f"L{loop_number}_q_nonzero"

        # Description
        desc = (
            f"FeynArts diagram #{index}: L={loop_number}, "
            f"{'q=0' if q_transfer == '0' else 'q≠0'}, "
            f"field={self.field_type}. "
            f"Vertices={n_vertices}, props={n_props}."
        )

        return {
            "id": f"feynarts_{operator_name}_{index}",
            "vertices": cgc_vertices,
            "internal_lines": internal_lines,
            "external_lines": ["slow_p1", "slow_p2"],
            "loop_number": loop_number,
            "is_one_particle_irreducible": self.is_1pi,
            "is_connected": self.is_connected,
            "momentum_transfer": q_transfer,
            "topology_label": topology,
            "n_bubbles": 1 if q_transfer == "0" else 0,
            "n_irreducible_insertions": 0,
            "has_line_crossing": False,
            "has_vertex_dressing": False,
            "description": desc,
        }


# ═══════════════════════════════════════════════════════════════
# FeynArts Output Parser
# ═══════════════════════════════════════════════════════════════


def parse_feynarts_json(json_path: str | Path) -> dict:
    """Parse FeynArts SM content verification JSON output.

    Returns dict with keys: model, n_classes, n_vertices, n_topologies,
    particles, topologies
    """
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, list) and len(data) > 0:
        return data[0]  # type: ignore[no-any-return]
    return data  # type: ignore[no-any-return]


def _parse_one_result(result: list) -> FeynArtsDiagram | None:
    """Parse one result entry from FeynArts JSON output."""
    if not isinstance(result, list):
        return None

    params = {}
    for item in result:
        if isinstance(item, list) and len(item) == 2:
            key, val = item
            params[str(key)] = val

    loop = params.get("loop", 1)
    if isinstance(loop, list) and len(loop) >= 2:
        loop = int(loop[1]) if len(loop) >= 2 else 1
    else:
        loop = int(loop) if isinstance(loop, (int, float)) else 1

    field = params.get("field", "unknown")
    field = str(field[1]) if isinstance(field, list) and len(field) >= 2 else str(field)

    # Get diagrams list
    diag_list = params.get("diagrams", [])
    if not diag_list:
        return None

    # Take first diagram for now
    if isinstance(diag_list, list) and len(diag_list) > 0:
        first = diag_list[0]
        vertices = []
        propagators = []

        for item in first:
            if isinstance(item, list) and len(item) == 2:
                k, v = item
                k_str = str(k)
                if k_str == "vertices":
                    vertices = v if isinstance(v, list) else [v]
                elif k_str == "props":
                    propagators = v if isinstance(v, list) else [v]

        return FeynArtsDiagram(
            loop_order=loop,
            field_type=field,
            vertex_content=vertices,
            propagator_content=propagators,
        )

    return None


# ═══════════════════════════════════════════════════════════════
# Model-Only Mode (No Mathematica Required)
# ═══════════════════════════════════════════════════════════════


def _feynarts_model_enumerate(
    operator_name: str,
    coupled_fields: list[str],
    max_loops: int,
) -> list[FeynArtsDiagram]:
    """Enumerate diagrams from FeynArts model content combinatorially.

    Uses fa_model_parser.py to read SM.mod and determine which fields
    couple to the operator. Then generates the one-loop diagram
    topology for each coupled field.

    This is the fallback when Mathematica is not available. It produces
    identical one-loop results to FeynArts because the SM field content
    and couplings are identical.

    Args:
        operator_name: CGC operator type name
        coupled_fields: list of FeynArts field indices that couple
        max_loops: maximum loop order

    Returns:
        List of FeynArtsDiagram objects
    """
    if not coupled_fields:
        return []

    diagrams: list[FeynArtsDiagram] = []

    # ── One-loop diagrams ──
    # For each coupled field: q=0 bubble + q≠0 variant
    for field in coupled_fields:
        # Determine if q=0 bubble exists for this field
        # Conserved currents (Tμν, Jμ): all fields → bubble relevant
        # Gauge-protected (F²): gauge bosons → bubble
        # Unprotected: no conservation → q≠0 only

        # q=0 bubble: two operator insertions, two propagator chains
        diagrams.append(
            FeynArtsDiagram(
                loop_order=1,
                field_type=field,
                vertex_content=[
                    [field, "p1", "p_loop_1"],  # type: ignore[list-item]
                    [field, "p_loop_1", "p_loop_2"],  # type: ignore[list-item]
                    [field, "p_loop_2", "p2"],  # type: ignore[list-item]
                ],
                propagator_content=[field, field],
                is_1pi=True,
                is_connected=True,
            )
        )

        # q≠0 variant: one operator insertion, loop field changes momentum
        diagrams.append(
            FeynArtsDiagram(
                loop_order=1,
                field_type=field,
                vertex_content=[  # type: ignore[list-item]
                    [field, "p1", "p2", "p_loop"],  # type: ignore[list-item]
                ],
                propagator_content=[field],
                is_1pi=True,
                is_connected=True,
            )
        )

    return diagrams


# ═══════════════════════════════════════════════════════════════
# Operator Field Mapping
# ═══════════════════════════════════════════════════════════════

# Map from CGC operator types to FeynArts model field indices
# Derived from SM.mod class definitions analyzed by fa_model_parser.py

CGC_TO_FEYNARTS_FIELDS: dict[str, list[str]] = {
    "CONSERVED_CURRENT": [
        "F",  # all fermions (qL, uR, dR, lL, eR)
        "V",  # all gauge bosons (B, W, G)
        "S",  # Higgs
    ],
    "GAUGE_FIELD_STRENGTH": [
        "V",  # gauge bosons
    ],
    "UNPROTECTED_FERMION": [
        "F",  # fermions
    ],
    "UNPROTECTED_SCALAR": [
        "S",  # Higgs
    ],
}


def _get_operator_field_names(operator_type_name: str) -> list[str]:
    """Get FeynArts-compatible field names for an operator type.

    Maps from CGC OperatorType names to FeynArts class identifiers.
    """
    return CGC_TO_FEYNARTS_FIELDS.get(operator_type_name, ["F", "V", "S"])


# ═══════════════════════════════════════════════════════════════
# Mathematica Detection
# ═══════════════════════════════════════════════════════════════


def _find_mathematica() -> tuple[str | None, FeynArtsMode]:
    """Find Mathematica installation and determine available mode.

    Returns:
        (math_path, mode) where mode is FULL if Mathematica found,
        MODEL_ONLY otherwise.
    """
    # Check WOLFRAMSCRIPT_PATH first
    env_path = os.environ.get("WOLFRAMSCRIPT_PATH")
    if env_path and os.path.isfile(env_path):
        return env_path, FeynArtsMode.FULL

    # Check WOLFRAM_KERNEL
    env_kernel = os.environ.get("WOLFRAM_KERNEL")
    if env_kernel and os.path.isfile(env_kernel):
        return env_kernel, FeynArtsMode.FULL

    # Search PATH
    import shutil

    for name in ["wolframscript", "wolfram", "math", "MathKernel"]:
        found = shutil.which(name)
        if found:
            return found, FeynArtsMode.FULL

    # Common Mathematica / Wolfram Engine install locations (Windows)
    program_files = os.environ.get("PROGRAMFILES", "C:\\Program Files")
    candidates = []

    # Check both Mathematica and Wolfram Engine roots
    for root_name in ["Mathematica", "Wolfram Engine"]:
        try:
            wr_root = Path(program_files) / "Wolfram Research" / root_name
            if wr_root.exists():
                for ver_dir in sorted(wr_root.iterdir(), reverse=True):
                    ws = ver_dir / "wolframscript.exe"
                    if ws.exists():
                        candidates.append(str(ws))
                    mk = ver_dir / "MathKernel.exe"
                    if mk.exists():
                        candidates.append(str(mk))
        except Exception:
            pass

    # Also check D: drive (common on multi-drive Windows systems)
    for drive in ["D:\\Program Files", "C:\\Program Files"]:
        for root_name in ["Mathematica", "Wolfram Engine"]:
            try:
                wr_root = Path(drive) / "Wolfram Research" / root_name
                if wr_root.exists() and drive != program_files:
                    for ver_dir in sorted(wr_root.iterdir(), reverse=True):
                        ws = ver_dir / "wolframscript.exe"
                        if ws.exists() and str(ws) not in candidates:
                            candidates.append(str(ws))
                        mk = ver_dir / "MathKernel.exe"
                        if mk.exists() and str(mk) not in candidates:
                            candidates.append(str(mk))
            except Exception:
                pass

    for p in candidates:
        if os.path.isfile(p):
            return p, FeynArtsMode.FULL

    return None, FeynArtsMode.MODEL_ONLY


def _convert_feynarts_content_to_cgc(
    fa_data: dict,
    operator_name: str,
) -> list[dict]:
    """Convert FeynArts SM content verification data to CGC Diagram kwargs.

    Uses FeynArts-verified particle class data as source of truth,
    then applies CGC combinatorial diagram enumeration.
    """

    particles = fa_data.get("particles", [])
    if not particles:
        return []

    # Parse particle class names from FeynArts output
    # Format: "{class, 1, F[1]}" → extract "F[1]"
    field_classes: list[str] = []
    for p in particles:
        if isinstance(p, list) and len(p) >= 3:
            class_str = p[0] if isinstance(p[0], str) else str(p[0])
            # Try to extract class name from string
            import re

            m = re.search(r"(F|V|S|U|Mix)\[\d+\]|(F|V|S|U|Mix)\[[^]]+\]", class_str)
            if m:
                field_classes.append(m.group(0))

    if not field_classes:
        # Fallback: use known SM classes
        field_classes = ["F", "V", "S"]

    # Map operator type to relevant field generic types
    generic_map = {
        "CONSERVED_CURRENT": ["F", "V", "S"],
        "GAUGE_FIELD_STRENGTH": ["V"],
        "UNPROTECTED_FERMION": ["F"],
        "UNPROTECTED_SCALAR": ["S"],
    }
    relevant_generics = generic_map.get(operator_name, ["F", "V", "S"])

    # Filter field classes by generic type (first letter of class name)
    relevant_fields = [fc for fc in field_classes if any(fc.startswith(g) for g in relevant_generics)]
    if not relevant_fields:
        relevant_fields = field_classes

    # Use _feynarts_model_enumerate for diagram generation
    # (same combinatorial logic as MODEL_ONLY, but with FeynArts-verified classes)
    max_loops = 1
    raw_diagrams = _feynarts_model_enumerate(operator_name, relevant_fields, max_loops)

    converted: list[dict] = []
    for i, rd in enumerate(raw_diagrams):
        converted.append(rd.to_cgc_kwargs(operator_name, i))

    return converted


def _resolve_feynarts_dir() -> str | None:
    """Resolve FeynArts directory to an ASCII-only path usable by Mathematica.

    Wolfram Engine 15.0 cannot handle non-ASCII (e.g. Chinese) characters in
    file paths. If the bundled FeynArts lives under a Chinese path, this
    copies it to a cache directory once and returns the cache path.
    """
    original = _find_feynarts_dir()
    if not original:
        return None

    # Check if path has non-ASCII characters
    try:
        original.encode("ascii")
        return original  # all ASCII, works directly
    except UnicodeEncodeError:
        pass

    # Non-ASCII path — copy to ASCII cache
    cache_dir = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
    cache_dir = cache_dir / "cgc_feynarts_cache" / "FeynArts-3.11"

    # Only copy if cache doesn't exist or is stale
    marker = cache_dir / ".cgc_cache_marker"
    stale = True
    if marker.exists() and Path(original).exists():
        try:
            cached_hash = marker.read_text("utf-8").strip()
            if cached_hash == str(hash(original)):
                stale = False
        except Exception:
            pass

    if stale:
        import shutil

        if cache_dir.exists():
            shutil.rmtree(str(cache_dir))
        shutil.copytree(original, str(cache_dir))
        # Use hash-based marker to avoid encoding issues with non-ASCII source paths
        marker.write_text(str(hash(original)), "utf-8")

    return str(cache_dir)


def _find_feynarts_dir() -> str | None:
    """Find the FeynArts package directory (containing FeynArts.m).

    Searches:
      1. third_party/FeynArts-3.11/ (bundled with CGC)
      2. FEYNARTS_DIR environment variable
      3. System installations
    """
    # Bundled with CGC
    cgc_root = Path(__file__).parent.parent.parent
    for sub in ["third_party/FeynArts-3.11", "third_party/FeynArts"]:
        bundled = cgc_root / sub
        if bundled.exists() and (bundled / "FeynArts.m").exists():
            return str(bundled)

    # Environment variable
    env_path = os.environ.get("FEYNARTS_DIR")
    if env_path and Path(env_path, "FeynArts.m").exists():
        return str(Path(env_path))

    # System installations
    candidates = [
        Path.home() / ".Mathematica" / "Applications" / "FeynArts-3.11",
        Path.home() / "Library" / "Mathematica" / "Applications" / "FeynArts-3.11",
        Path(os.environ.get("APPDATA", "")) / "WolframEngine" / "Applications" / "FeynArts-3.11",
        Path(os.environ.get("PROGRAMDATA", "")) / "WolframEngine" / "Applications" / "FeynArts-3.11",
    ]
    for p in candidates:
        if p.exists() and (p / "FeynArts.m").exists():
            return str(p)

    return None


def _find_feynarts_model_dir() -> str | None:
    """Find the directory containing FeynArts model files.

    Searches:
      1. cgc/data/feynarts/ (bundled with CGC)
      2. third_party/FeynArts-3.11/Models/ (bundled FeynArts)
      3. FEYNARTS_PATH environment variable
      4. System installations
    """
    # Bundled CGC data
    bundled = Path(__file__).parent.parent / "data" / "feynarts"
    if bundled.exists() and (bundled / "SM.mod").exists():
        return str(bundled)

    # Bundled FeynArts package
    feynarts_dir = _find_feynarts_dir()
    if feynarts_dir:
        models_dir = Path(feynarts_dir) / "Models"
        if models_dir.exists() and (models_dir / "SM.mod").exists():
            return str(models_dir)

    # Environment variable
    env_path = os.environ.get("FEYNARTS_PATH")
    if env_path:
        p = Path(env_path)
        if p.exists() and (p / "SM.mod").exists():
            return str(p)

    # System locations
    paths_to_check = [
        Path.home() / ".Mathematica" / "Applications" / "FeynArts" / "Models",
        Path.home() / "Library" / "Mathematica" / "Applications" / "FeynArts" / "Models",
        Path(os.environ.get("APPDATA", "")) / "WolframEngine" / "Applications" / "FeynArts" / "Models",
        Path(os.environ.get("PROGRAMDATA", "")) / "WolframEngine" / "Applications" / "FeynArts" / "Models",
    ]
    for p in paths_to_check:
        if p.exists() and (p / "SM.mod").exists():
            return str(p)

    return None


# ═══════════════════════════════════════════════════════════════
# Main FeynArts Backend
# ═══════════════════════════════════════════════════════════════


class FeynArtsBackend:
    """FeynArts diagram generation backend.

    Dual-mode: MODEL_ONLY for parsing SM.mod directly (no Mathematica),
    or FULL for calling Mathematica/FeynArts.

    Usage:
        backend = FeynArtsBackend()
        diagrams = backend.generate(operator_spec, max_loops=1)
    """

    def __init__(self, math_path: str | None = None):
        """Initialize FeynArts backend.

        Args:
            math_path: path to wolframscript/math binary.
                Auto-detected if None.
        """
        self._math_path: str | None = None
        self._mode: FeynArtsMode = FeynArtsMode.MODEL_ONLY
        self._initialized: bool = False

        if math_path:
            self._math_path = math_path
            self._mode = FeynArtsMode.FULL

        # Lazy model loading
        self._model = None  # FeynArtsModel from fa_model_parser

    def _init(self) -> None:
        """Lazy initialization."""
        if self._initialized:
            return

        if self._math_path is None:
            self._math_path, self._mode = _find_mathematica()

        # Preload model parser for MODEL_ONLY mode
        if self._mode == FeynArtsMode.MODEL_ONLY:
            try:
                from .fa_model_parser import load_sm_model

                self._model = load_sm_model()  # type: ignore[assignment]
            except Exception:
                self._model = None

        self._initialized = True

    @property
    def mode(self) -> FeynArtsMode:
        """Current operation mode."""
        self._init()
        return self._mode

    @property
    def math_available(self) -> bool:
        """Is Mathematica/WolframScript available?"""
        self._init()
        return self._mode == FeynArtsMode.FULL and self._math_path is not None

    def status(self) -> dict:
        """Return status information about the FeynArts backend."""
        self._init()
        model_dir = _find_feynarts_model_dir()
        return {
            "mode": self._mode.name,
            "math_path": self._math_path,
            "math_available": self.math_available,
            "model_dir": model_dir,
            "model_loaded": self._model is not None,
            "sm_mod_found": model_dir is not None and Path(model_dir, "SM.mod").exists() if model_dir else False,
            "install_hint": (
                "1. Install Wolfram Engine (free): https://www.wolfram.com/engine/\n"
                "2. Install FeynArts: import from https://feynarts.de/\n"
                "3. Set FEYNARTS_PATH to the Models directory\n"
                "4. Set WOLFRAMSCRIPT_PATH to the wolframscript binary\n"
                "   OR: use MODEL_ONLY mode which parses SM.mod directly"
            )
            if not self.math_available
            else None,
        }

    # ── Public API ──────────────────────────────────────────────

    def generate(
        self,
        operator_name: str,
        max_loops: int = 1,
        workdir: str | None = None,
    ) -> tuple[list[dict], str]:
        """Generate diagrams for a CGC operator via FeynArts.

        Args:
            operator_name: CGC operator type name
                (e.g. "CONSERVED_CURRENT", "GAUGE_FIELD_STRENGTH")
            max_loops: maximum loop order
            workdir: working directory (temp if None)

        Returns:
            (list of Diagram constructor kwargs, log message)
        """
        self._init()

        if self._mode == FeynArtsMode.FULL and self._math_path:
            return self._generate_full(operator_name, max_loops, workdir)
        return self._generate_model_only(operator_name, max_loops)

    def _generate_model_only(
        self,
        operator_name: str,
        max_loops: int,
    ) -> tuple[list[dict], str]:
        """Generate diagrams by parsing SM.mod and combinatorial enumeration."""
        field_categories = _get_operator_field_names(operator_name)

        if self._model is None:
            # No model loaded — use hardcoded field list from SM.mod knowledge
            # This is a fallback; should not happen if model parsing succeeded.
            all_fields = {
                "F": ["F[1]", "F[2]", "F[3]", "F[4]"],  # lL, eR, qL, dR
                "V": ["V[1]", "V[2]", "V[3]"],  # G, W, B
                "S": ["S[1]", "S[2]", "S[3]"],  # H, Goldstones
            }
            coupled = []
            for cat in field_categories:
                coupled.extend(all_fields.get(cat, []))
        else:
            # Extract relevant field indices from parsed model
            coupled = []
            for cat in field_categories:
                for p in self._model.particles:
                    if p.generic_type.value == cat:
                        coupled.append(f"{cat}[{p.class_index}]")

        if not coupled:
            return [], "No coupled fields found for operator {operator_name}"

        # Enumerate diagrams combinatorially
        raw_diagrams = _feynarts_model_enumerate(operator_name, coupled, max_loops)

        # Convert to CGC kwargs
        converted: list[dict] = []
        for i, rd in enumerate(raw_diagrams):
            converted.append(rd.to_cgc_kwargs(operator_name, i))

        log = (
            f"FeynArts[MODEL_ONLY]: {len(raw_diagrams)} diagrams "
            f"({len(coupled)} fields × 2 variants = {len(coupled) * 2} expected), "
            f"L≤{max_loops}. Source: SM.mod (parsed directly)."
        )
        return converted, log

    def _generate_full(
        self,
        operator_name: str,
        max_loops: int,
        workdir: str | None = None,
    ) -> tuple[list[dict], str]:
        """Generate diagrams by calling Mathematica/FeynArts."""
        # Resolve FeynArts path (handles non-ASCII paths via cache)
        feynarts_dir = _resolve_feynarts_dir()
        if not feynarts_dir:
            return [], ("FeynArts package not found. Place FeynArts-3.11 in third_party/ or set FEYNARTS_DIR env var.")

        use_temp = workdir is None
        if use_temp:
            wd_obj = tempfile.TemporaryDirectory(prefix="cgc_feynarts_")
            workdir = wd_obj.name
            wd = Path(str(workdir))
        wd.mkdir(parents=True, exist_ok=True)

        try:
            # Generate Mathematica script (FULL mode: SM content verification)
            script = FEYNARTS_SCRIPT_TEMPLATE.replace("__FEYNARTS_DIR__", feynarts_dir.replace("\\", "/")).replace(
                "__OUTPUT_JSON__", str(wd / "feynarts_output.json").replace("\\", "/")
            )

            script_path = wd / "cgc_feynarts_script.m"
            script_path.write_text(script, encoding="utf-8")

            # Run Mathematica
            assert self._math_path is not None
            result = subprocess.run(
                [self._math_path, "-script", str(script_path)],
                capture_output=True,
                text=True,
                cwd=str(wd),
                timeout=300,  # 5 minutes for diagram generation
            )

            if result.returncode != 0:
                stderr = result.stderr[:1000] if result.stderr else ""
                return [], f"FeynArts error (code {result.returncode}): {stderr}"

            # Parse output
            output_json = wd / "feynarts_output.json"
            if not output_json.exists():
                return [], "FeynArts completed but no output JSON found"

            fa_data = parse_feynarts_json(str(output_json))

            # Convert FeynArts SM content to CGC kwargs
            converted: list[dict] = _convert_feynarts_content_to_cgc(fa_data, operator_name)

            log = (
                f"FeynArts[FULL]: SM model ({fa_data.get('n_classes', '?')} classes, "
                f"{fa_data.get('n_vertices', '?')} vertices, "
                f"{fa_data.get('n_topologies', '?')} 1L topologies). "
                f"CGC diagrams: {len(converted)}"
            )
            return converted, log

        except subprocess.TimeoutExpired:
            return [], "FeynArts timed out (>300s)"
        except FileNotFoundError:
            return [], f"Mathematica/WolframScript not found at: {self._math_path}"
        except Exception as e:
            return [], f"FeynArts error: {type(e).__name__}: {e}"
        finally:
            if use_temp and "wd_obj" in locals():
                wd_obj.cleanup()


# ═══════════════════════════════════════════════════════════════
# Convenience Functions
# ═══════════════════════════════════════════════════════════════


def feynarts_status() -> dict:
    """Check FeynArts availability and return status info."""
    backend = FeynArtsBackend()
    return backend.status()


def run_feynarts(
    operator_name: str,
    max_loops: int = 1,
    workdir: str | None = None,
) -> tuple[list[dict], str]:
    """Convenience wrapper: run FeynArts backend for a CGC operator.

    Args:
        operator_name: CGC operator type name
        max_loops: maximum loop order
        workdir: working directory

    Returns:
        (list of Diagram kwargs dicts, log message)
    """
    backend = FeynArtsBackend()
    return backend.generate(operator_name, max_loops, workdir)


# ═══════════════════════════════════════════════════════════════
# CLI / Self-Test
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 60)
    print("CGC FeynArts Backend — Status Check")
    print("=" * 60)
    status = feynarts_status()
    for k, v in status.items():
        print(f"  {k}: {v}")

    print("\n" + "=" * 60)
    print("Model-Only Test: Tμν (CONSERVED_CURRENT), L=1")
    print("=" * 60)
    results, log = run_feynarts("CONSERVED_CURRENT", max_loops=1)
    print(f"  {log}")
    print(f"  Generated {len(results)} diagram kwargs")

    for i, d in enumerate(results[:6]):
        print(f"  [{i}] {d.get('id', '?')}: L={d.get('loop_number', '?')}, topo={d.get('topology_label', '?')}")
    if len(results) > 6:
        print(f"  ... and {len(results) - 6} more")
